apiVersion: v2
name: 'http-https-echo'
description: Connected Facilities http echo debug utility
keywords:
  - 'connected-facilities'
  - 'http-echo-debug-front-end'
type: application
home: ''  # The URL of this projects home page (optional)
sources: []  # A list of URLs to source code for this project (optional)
maintainers:
  - name: 'Paul Charlton'
    email: 'techguru@byiq.com'
    url: 'https://www.gitlab.com/techguru'
icon: ''
deprecated: false

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 'r0.2.0-dev'

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.2.0-dev
